openapi: 3.0.0
info:
  title: K6 Load Test API
  description: |-
    K6 Load Test API
  version: 1.0.0
servers:
  - url: 'http://localhost:{port}/jester/'
    description: dev
    variables:
      port:
        default: '8080'
  - url: 'https://api.<domain-name>/jester/'
    description: stg

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /healthcheck:
    get:
      tags:
        - healthcheck
      summary: Checks the health of the API
      description: Returns a simple status object indicating the API is up and running.
      operationId: healthcheck
      responses:
        '200':
          description: API is up and running
          content:
            application/json:
              schema:
                $ref: './api/responses/HealthCheck.yaml'
      security: []  # healthcheckでは認証を必要としないため
  /v1/users:
    $ref: './api/v1/paths/User.yaml'
  /v1/users/me:
    $ref: './api/v1/paths/Me.yaml'
