services:
  shop-api:
    platform: linux/amd64
    image: cosmtrek/air:v1.61.0
    container_name: shop-api
    working_dir: /go/src/github.com/tamaco489/k6_load_test/api/shop
    volumes:
      - ./shop:/go/src/github.com/tamaco489/k6_load_test/api/shop
      - ~/.cache/go-build:/root/.cache/go-build
    ports:
      - "8080:8080"

  k6:
    platform: linux/amd64
    image: grafana/k6:latest
    container_name: k6
    command: run /_tools/k6/dist/main.js
    volumes:
      - ./_tools/k6/dist:/_tools/k6/dist
